before_install:
  sudo apt-get install build-essential autoconf automake libtool libcppunit-dev python-setuptools python-dev
script:
  cd scripts
  sudo ./build.sh
  
  sudo ./arcus.sh quicksetup conf/local.sample.json

