before_install:
  sudo apt-get install build-essential autoconf automake libtool libcppunit-dev python-setuptools python-dev
script:
  cd scripts
  sudo ./build.sh
  
  # Setup a local cache cloud with conf file. (Should be non-root user)
  ./arcus.sh quicksetup conf/local.sample.json

  # Test
  echo "stats" | nc localhost 11211 | grep version
  echo "stats" | nc localhost 11212 | grep version
